mozilla/delivery-dashboard

.eslintrc.js
package.json
src/App.css
src/App.js
src/App.test.js
src/index.js
src/registerServiceWorker.js
yarn.lock

Add eslint and prettier

---

.travis.yml

Add travis to run the linting

---

README.md

Update instructions to run the project in the README

---

.eslintrc.js
package.json
src/App.js
src/App.test.js
src/index.js
src/registerServiceWorker.js
yarn.lock

Properly fail travis build on prettier formating rules as well as eslint

---

.eslintrc.js
src/App.js

Add a navigation URL

---

src/App.js
src/actions.js
src/types.js

Type the Pollbot API responses

---

src/App.js

Remove the release dashboard item

---

src/App.css
src/App.js
src/PollbotAPI.js
src/actions.js
src/reducers.js
src/types.js

Integrate the new Pollbot API

---

src/App.js
src/actions.js

Only auto-refresh once, not once per component update

---

src/App.js
src/actions.js

Fixes #59
Deployed to [github pages](https://mozilla.github.io/delivery-dashboard/) for testing ;)

Display spinners when auto-refreshing

---

.gitignore
package.json
src/App.css
src/App.js
src/PollbotAPI.js
src/actions.js
src/reducers.js
src/types.js
update_version.sh
version.json

Display the version of the UI and Pollbot

---

.flowconfig
package.json
src/App.js
yarn.lock

Update all the dependencies to their latest version

---

src/PollbotAPI.js
src/actions.js

Switch to async/await

---

package.json
src/App.js
src/App.test.js

Treat errors as every other status

---

src/App.js
src/App.test.js
src/actions.js
src/actions.test.js
src/reducers.js
src/reducers.test.js
src/types.js

Don't notify status changes when changing versions

---

src/create-store.js

Very convenient, check https://github.com/zalmoxisus/redux-devtools-extension

Use redux devtools

---

package.json
src/App.js
src/actions.js
src/actions.test.js
src/create-store.js
src/sagas.js
src/sagas.test.js
src/types.js
yarn.lock

Use redux-sagas

---

src/sagas.js
src/sagas.test.js

Check results in parallel

---

src/App.js
src/actions.js
src/actions.test.js
src/reducers.js
src/types.js

List all ongoing versions, listed by descending version

---

src/App.css
src/App.js
src/__snapshots__/App.test.js.snap

Responsive design

---

src/sagas.js
src/sagas.test.js

Fixes #81. Again. I hope.
Refs https://github.com/mozilla/delivery-dashboard/pull/83#pullrequestreview-66177387
How was it even working. I can't even

Fix the 'run checks in parallel'. I hope.

---

src/App.js
src/App.test.js

Display the overall status of a release

---

public/index.html
src/App.css
src/App.js
src/App.test.js
src/__snapshots__/App.test.js.snap
src/actions.js
src/actions.test.js
src/auth0.js
src/auth0.test.js
src/reducers.js
src/reducers.test.js
src/sagas.js
src/sagas.test.js
src/types.js

Add auth0 login

---

.travis.yml
package.json
src/auth0.js
yarn.lock

Fix codecov

---

package.json

fix(package): update react-scripts to version 1.0.16

---

src/App.js
src/App.test.js

Only display an overall release status when we have all the check results

---

src/App.css

Avoiding the alert texts cads break up the container

---

src/PollbotAPI.test.js

Relax the tests to not break on non breaking API changes

---

package.json
yarn.lock

fix(package): update photon-ant to version 0.1.4

---

flow-typed/overrides/photon-ant.js
package.json
src/App.js
yarn.lock

chore(package): update flow-bin to version 0.63.1

---

package.json
yarn.lock

Update the 'marked' dependency which had a security issue

---

src/App.js
src/App.test.js
src/__snapshots__/App.test.js.snap
src/actions.js
src/actions.test.js
src/reducers.js
src/reducers.test.js
src/sagas.js
src/sagas.test.js
src/types.js

Better use of colours for the check results and overall status

---

src/App.js
src/App.test.js
src/types.js

Use the actionable flag for checks

---

src/App.js
src/actions.js
src/actions.test.js
src/reducers.js
src/reducers.test.js
src/sagas.js
src/sagas.test.js
src/types.js

Only refresh checks that were previously failing

---

src/App.js
src/PollbotAPI.js
src/actions.js
src/actions.test.js
src/reducers.js
src/sagas.js
src/sagas.test.js
src/types.js

Fixes #151 
I started to figure out a way to do that but it needs a lot of improvments.
@magopian feel free to take over if you want or we can also plan a meeting to talk about it.

Handle channels name as version number aliases.

---

src/App.js
src/App.test.js
src/sagas.js
src/sagas.test.js
src/types.js

Display ongoingVersion fetch errors.

---

src/App.js
src/App.test.js
src/__snapshots__/App.test.js.snap
src/actions.js
src/actions.test.js
src/reducers.js
src/reducers.test.js
src/types.js

Remove the (now useless) search box

---

src/App.js

More informative titles for a results page

---

src/App.js

Change the glyphicon for non-actionable checks

---

src/App.js
src/App.test.js
src/PollbotAPI.js
src/PollbotAPI.test.js
src/__snapshots__/App.test.js.snap
src/actions.js
src/actions.test.js
src/reducers.js
src/reducers.test.js
src/sagas.js
src/sagas.test.js
src/types.js

Add the new 'devedition' product

---

src/App.js
src/App.test.js
src/__snapshots__/App.test.js.snap

Merge devedition version with firefox ones in the left menu

---

src/App.js
src/PollbotAPI.test.js

Pollbot now uses 'aurora' for the devedition channel. Fixes #167

---

src/App.js
src/__snapshots__/App.test.js.snap

Hide the login button until we need it. Fixes #169

---

src/App.js

It made my iPhone happier.
I unfortunately don't know how to run tests yet :(
```
▶ yarn test
yarn run v1.3.2
warning ../../../../package.json: No license field
$ NODE_ENV=test react-app-rewired test --env=jsdom --silent
2018-02-01 14:22 node[6720] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-02-01 14:22 node[6720] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:182
throw er; // Unhandled 'error' event
^
Error: Error watching file for changes: EMFILE
at _errnoException (util.js:1022:11)
at FSEvent.FSWatcher._handle.onchange (fs.js:1359:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this …
```

Avoid Notification if not supported, fixes #171

---

src/App.css

nicer alignment on mobile

---

package.json
src/PollbotAPI.js

https://whatsdeployed.io/s-D5S

Use the production endpoint.

---

src/PollbotAPI.test.js
src/types.js

The API __version__ now returns a 'build' field
